feat: inclusao de icone de processo recebido pelo barramento
supergovbr/mod-sei-pen pull request #191
Opened 2022-11-16 14:15 UTC by Mauro1706

Inclusão de ícone para processo recebido do barramento

2022-11-30 00:15 UTC, higodf requested changes
O tramite ainda no status 2 e já aparece o icone com a informação "Um trâmite para esse processo foi recebido"

![image](https://user-images.githubusercontent.com/67421451/204676290-49d35f36-4ac9-49dd-8516-066fa549d766.png)

O correto seria apresentar o icone apenas quando o status for 5 ou 6. Da forma como está o usuário vai entender que o tramite foi finalizado quando ainda está no status 2

2022-12-08 12:23 UTC, Mauro1706 commented
Alterado código para status 5 e 6

2022-12-13 13:29 UTC, higodf requested changes
Conforme reunião de sexta-feira, dia 09/12, ficou acordado que essa implementação seria refeita.

2022-12-13 13:51 UTC, Mauro1706 commented
Implementação foi refeita, commit de hoje

2023-02-16 14:38 UTC, Mauro1706 commented
Boa dia Higo, como estamos trabalhando em fork e não tenho mais acesso a subir no projeto criei um no PR forkeado:
https://github.com/supergovbr/mod-sei-pen/pull/222/files

2023-03-09 17:46 UTC, higodf commented
Está sendo tratado em outro PR

2023-04-23 23:42 UTC, guilhermeadc commented
Prezados, 

Durante os testes desta funcionalidade, foram identificados dois pequenos problemas que precisam ser ajustados antes de serem aceitos e incorporados ao mod-sei-pen.

1) O ícone indicativo de processo recebido pelo Tramita.gov.br está se repetindo inúmeras vezes, 1 para cada trâmite já realizado pelo processo, conforme demonstrado abaixo.
![image](https://user-images.githubusercontent.com/4326504/233872119-a772055e-4baa-404e-b07c-1a8a5bb36f85.png)

O comportamento correto deveria ser a apresentação de apenas 1 ícone indicando que o último recebimento.

2) Quando este processo é enviado para outra unidade, o ícone continua aparecendo, indicando que o processo chegou pelo Tramita.gov.br, fato que não é verdade já que ele foi recebido proveniente de outra unidade.
![image](https://user-images.githubusercontent.com/4326504/233872263-edf370b7-5cd8-4246-9cbf-d2a15d4677f7.png)

O comportamento esperado neste caso em que um processo recebido pelo Tramita.gov.br e depois enviado para outra unidade seria não apresentar o ícone já que o mesmo foi recebido na unidade TESTE_1_1 por envio simples de uma unidade para outra.

Para reproduzir este segundo caso, os seguintes passos devem ser realizados:
1) Enviar um processo do órgão 1 para o órgão 2 
2) No órgão 2, identificar o processo e verificar se o ícone está aparecendo (comportamento esperado)
3) Enviar o mesmo processo para a unidade SEI TESTE_1_1
4) Mudar o contexto da unidade no SEI de TESTE para TESTE_1_1
5) Identificar o processo e verificar que o ícone nâo está sendo apresentado (comportamento esperado já que ele foi recebido de outra unidade do SEI, e nâo do Tramita.gov.br.

2023-05-26 19:03 UTC, gicastephanou requested changes
Prezado Mauro,
Solicito que resolva o conflito no seguinte arquivo: src/PENIntegracao.php e encaminhe novamente para validação.

2023-06-15 14:09 UTC, Mauro1706 commented
Prezados,
Depois de conversas com PO e o Guilherme Cantoni foi avaliado e resolvido as implementações faltando no PR https://github.com/supergovbr/mod-sei-pen/pull/232

2023-06-15 14:09 UTC, closed without merging