feat: Adicionar verificação na chamada da constante CURLOPT_SSL_VERIFYHOST
supergovbr/mod-sei-pen pull request #194
Opened 2022-11-21 04:21 UTC by mrglaydson

closes ([#188](https://github.com/supergovbr/mod-sei-pen/issues/188))

2022-11-22 13:09 UTC, caduvieira requested changes
Precisa tanto do VERIFY_HOST como PEER para minimizar o ataque MITM https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html Não há outros pontos de verificação? Após esa alteração como o localhost se comportou?

2022-12-01 18:02 UTC, mrglaydson commented
teste webservice local

https://user-images.githubusercontent.com/11926294/205127058-6f276df0-3a89-4eed-9758-aca75c229d8a.mp4

2022-12-08 14:40 UTC, caduvieira commented
@mrglaydson falta esclarecimentos sobre o review que abri.

2022-12-08 14:40 UTC, caduvieira requested changes

2022-12-08 18:53 UTC, caduvieira approved these changes

2022-12-09 02:15 UTC, higodf approved these changes

2022-12-20 13:05 UTC, merged