feat: melhoria na mensagem de alteração de ordem de documentos do processo
supergovbr/mod-sei-pen pull request #202
Opened 2022-12-30 14:17 UTC by Mauro1706

2023-01-12 14:38 UTC, caduvieira requested changes
No objeto objMetadadosProcessoTramiteAnterior é possível pegar os dados do documento que deu problema e a partir disso pegar o array de componentes digitais e pegar o nome dele. obterTamanhoComponenteDigitalPendente em ReceberProcedimentoRN pode te auxiliar em como obter os dados.

Os XSD do tramita está em anexo
[tramitaxsd.zip](https://github.com/supergovbr/mod-sei-pen/files/10402641/tramitaxsd.zip)

2023-02-15 00:44 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +        $objMetadadosProcessoTramiteAnterior = null;
Excluir as linhas 574 a 600

2023-02-15 00:45 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +            $arrObjAtividadeDTO = $objAtividadeBD->listar($objAtividadeDTO);
Usar a classe AtividadeRN  e o método contarRN0035

2023-02-15 00:46 UTC, higodf commented on src/rn/ProcessoEletronicoRN.php
> +                $strMensagem = str_replace('hash de ao menos um componente digital n�o confere', 'a ordem dos documentos foram modificadas na �rvore do processo', $strMensagem);
Substituir a mensagem por "Possivelmente a falha ocorreu devido a mudança de ordem do documento na árvore do processo."

2023-04-24 04:18 UTC, guilhermeadc commented
Nâo foi possível aceitar o merge pois o Pull Request está com inúmeros problemas de encode de caracteres (deve ser usado isso), quebra nas acentuações das palavras dos arquivos modificados, e diferença em relação ao carácter de quebra de linha.

Revisar as configurações da IDE de desenvolvimento utilizada e avaliar o uso dos padrões utilizados pelo sistema:
- ISO8859-1
- Quebra de linha: LF (Linux).Não utilizar a quebra do windows (Windows: CRLF)

No mais, a implementação parece estar funcionando adequadamente, conforme solicitado.

2023-05-29 19:28 UTC, davidnascimento1618 reviewed
Foi verificado que a mensagem que está sendo exibida para o usuário, está ficando muito extensa, principalmente quando há uma quantidade considerável de documentos anexados ao processo, esta mensagem, além de apontar o problema, tem o intuito de orientar o usuário para a devida solução do problema, isto é, da ordenação íntegra destes documentos dentro do processo. Analisaremos internamente uma melhor forma de tratar tal questão.

2023-06-02 21:39 UTC, guilhermeadc commented
Este Pull Request será fechado sem merge com a branch principal. Isso será feito pois o desenvolvimento continuará a ser aprimorado através do Issue #261 em que mudanças na forma de apresentação da mensagem foram solicitadas.

2023-06-02 21:39 UTC, closed without merging